name: ift-6135-hw2
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyter
  - ipywidgets
  - tqdm
  # - pip:
  #   - torch
  #   - torchvision
